#!/usr/bin/env bash
# panebot-geometry.sh
# Usage: panebot-geometry.sh [layout-name]
# Requires panebot panes to be running with --title set to pane name (uppercase)

LAYOUT_NAME="${1:-captured}"
LAYOUT_DIR="$HOME/.config/panebot/layouts"
PANES_CONF="$HOME/.config/panebot/pb.panes.conf"
OUTPUT="$LAYOUT_DIR/$LAYOUT_NAME.layout"

mkdir -p "$LAYOUT_DIR"

PANE_NAMES=$(grep '^\[' "$PANES_CONF" | tr -d '[]')

if [[ -z "$PANE_NAMES" ]]; then
    echo "No panes found in $PANES_CONF"
    exit 1
fi

echo "# panebot layout — $LAYOUT_NAME" > "$OUTPUT"
echo "# Generated by panebot-geometry.sh" >> "$OUTPUT"
echo "" >> "$OUTPUT"

COUNT=0
while read -r name; do
    TITLE=$(echo "$name" | tr '[:lower:]' '[:upper:]')
    RESULT=$(osascript << APPLESCRIPT
tell application "System Events"
    try
        repeat with proc in (every process whose name is "mpv")
            repeat with win in (every window of proc)
                if name of win is "$TITLE" then
                    set pos to position of win
                    set sz to size of win
                    set px to (item 1 of pos) as text
                    set py to (item 2 of pos) as text
                    set pw to (item 1 of sz) as text
                    set ph to (item 2 of sz) as text
                    return px & " " & py & " " & pw & " " & ph
                end if
            end repeat
        end repeat
    end try
end tell
APPLESCRIPT
    )
    [[ -z "$RESULT" ]] && echo "  $name → not found, skipping" && continue
    x=$(echo "$RESULT" | awk '{gsub(/,/,"",$1); print $1*2}')
    y=$(echo "$RESULT" | awk '{gsub(/,/,"",$2); print $2*2}')
    w=$(echo "$RESULT" | awk '{gsub(/,/,"",$3); print $3*2}')
    h=$(echo "$RESULT" | awk '{gsub(/,/,"",$4); print $4*2}')
    echo "  $name → ${w}x${h}+${x}+${y}"
    echo "[$name]" >> "$OUTPUT"
    echo "geometry = ${w}x${h}+${x}+${y}" >> "$OUTPUT"
    echo "" >> "$OUTPUT"
    COUNT=$((COUNT + 1))
done <<< "$PANE_NAMES"

echo ""
echo "Captured $COUNT pane(s). Saved to: $OUTPUT"
echo "Switch to it in panebot with [W]"
