#!/usr/bin/env bash
# panebot-geometry.sh
# Usage: panebot-geometry.sh [layout-name]

LAYOUT_NAME="${1:-captured}"
LAYOUT_DIR="$HOME/.config/panebot/layouts"
OUTPUT="$LAYOUT_DIR/$LAYOUT_NAME.layout"

mkdir -p "$LAYOUT_DIR"

RAW=$(osascript << 'APPLESCRIPT'
tell application "System Events"
    set result to ""
    set mpv_list to every process whose name is "mpv"
    repeat with proc in mpv_list
        try
            set win_list to every window of proc
            repeat with win in win_list
                try
                    set wtitle to name of win
                    set pos to position of win
                    set sz to size of win
                    set px to (item 1 of pos) as text
                    set py to (item 2 of pos) as text
                    set pw to (item 1 of sz) as text
                    set ph to (item 2 of sz) as text
                    set result to result & wtitle & " " & px & " " & py & " " & pw & " " & ph & ASCII character 10
                end try
            end repeat
        end try
    end repeat
    return result
end tell
APPLESCRIPT
)

if [[ -z "$RAW" ]]; then
    echo "No mpv windows found."
    exit 1
fi

echo "DEBUG:"
echo "$RAW"
echo "---"

echo "# panebot layout — $LAYOUT_NAME" > "$OUTPUT"
echo "# Generated by panebot-geometry.sh" >> "$OUTPUT"
echo "" >> "$OUTPUT"

COUNT=0
while read -r title x y w h; do
    [[ -z "$title" || -z "$w" || -z "$h" ]] && continue
    # strip commas from numbers (AppleScript quirk)
    x=${x//,/}; y=${y//,/}; w=${w//,/}; h=${h//,/}
    [[ "$w" -lt 10 || "$h" -lt 10 ]] 2>/dev/null && continue
    slot=$(echo "$title" | tr '[:upper:]' '[:lower:]')
    echo "  $slot → ${w}x${h}+${x}+${y}"
    echo "[$slot]" >> "$OUTPUT"
    echo "geometry = ${w}x${h}+${x}+${y}" >> "$OUTPUT"
    echo "" >> "$OUTPUT"
    COUNT=$((COUNT + 1))
done <<< "$(echo "$RAW" | grep -v '^$' | sort -k3,3n -k2,2n)"

echo ""
echo "Found $COUNT pane(s). Saved to: $OUTPUT"
echo "Switch to it in panebot with [W]"
